[project]
name = "ComfyUI-TagForge"
description = "Tag completer with wildcard sub-selection and CSV file support"
version = "2.1.2"
license = {file = "LICENSE"}
dependencies = []

[project.urls]
Repository = "https://github.com/huchukato/ComfyUI-TagForge"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "huchukato"
DisplayName = "ComfyUI-TagForge"
Icon = "https://raw.githubusercontent.com/huchukato/ComfyUI-TagForge/main/icon.png"
Banner = "https://raw.githubusercontent.com/huchukato/ComfyUI-TagForge/main/banner.png"
requires-comfyui = ">=1.0.0"
